baseurl = "http://100.100.100.251:1313/"
languageCode = "en-us"
title = "Dewret"
theme = "hyde"
googleAnalytics = "UA-81141436-1"
disqusShortname = "wwwdewretcoza"

[permalinks]
        post = "/:year/:month/:title/"
        code = "/:filename/"
        page = "/:title/"
        about = "/:filename/"

[[menu.main]]
    name = "About"
    url = "/about/"

[params]
    description = "third-person, singular, simple, present"

[taxonomies]
        tag = "tags"
        category = "categories"
        series = "series"

