title = "Dewret"
baseurl = "https://www.dewret.co.za"
languageCode = "en-us"
theme = "startbootstrap-clean-blog"
canonifyurls = true
paginate = 10

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
googleAnalytics = "UA-81141436-1"
disqusShortname = "wwwdewretcoza"
enableRobotsTXT = true

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "third-person, singular, simple, present"
  Author = "Dewret"
  postSummariesFrontPage = 10
  showReadTime = true

[social]
  twitter = "https://twitter.com/dewretsa"
  github = "https://github.com/dewret"

[permalinks]
        post = "/:year/:month/:title/"
        code = "/:filename/"
        page = "/:title/"
        about = "/:filename/"

[taxonomies]
        tag = "tags"
        category = "categories"
        series = "series"

[[menu.main]]
  name = "about"
  url = "/about/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
